/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface PhoditHeader {
    }
}
declare global {
    interface HTMLPhoditHeaderElement extends Components.PhoditHeader, HTMLStencilElement {
    }
    var HTMLPhoditHeaderElement: {
        prototype: HTMLPhoditHeaderElement;
        new (): HTMLPhoditHeaderElement;
    };
    interface HTMLElementTagNameMap {
        "phodit-header": HTMLPhoditHeaderElement;
    }
}
declare namespace LocalJSX {
    interface PhoditHeader {
    }
    interface IntrinsicElements {
        "phodit-header": PhoditHeader;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "phodit-header": LocalJSX.PhoditHeader & JSXBase.HTMLAttributes<HTMLPhoditHeaderElement>;
        }
    }
}
