/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */

import '@stencil/core';

declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLElement {
    componentOnReady?: () => Promise<this | null>;
  }

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}
}


declare global {

  namespace StencilComponents {
    interface PhoditHeader {
      'action': string;
    }
  }

  interface HTMLPhoditHeaderElement extends StencilComponents.PhoditHeader, HTMLStencilElement {}

  var HTMLPhoditHeaderElement: {
    prototype: HTMLPhoditHeaderElement;
    new (): HTMLPhoditHeaderElement;
  };
  interface HTMLElementTagNameMap {
    'phodit-header': HTMLPhoditHeaderElement;
  }
  interface ElementTagNameMap {
    'phodit-header': HTMLPhoditHeaderElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'phodit-header': JSXElements.PhoditHeaderAttributes;
    }
  }
  namespace JSXElements {
    export interface PhoditHeaderAttributes extends HTMLAttributes {
      'action'?: string;
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }

export declare function defineCustomElements(window: any): void;