export const EventConstants = {
  TEMP_FILE_STATUS: "phodit.temp.file.status",
  PHODIT: {
    OPEN_PATH: "phodit.open.path",
    RELOAD_PATH: "phodit.reload.path",
    SAVE_FILE: "phodit.save.file",
    OPEN_ONE_FILE: "phodit.open.one-file",
    OPEN_FILE: "phodit.open.file",
    SUGGEST_SEND: "phodit.suggest.send",
    SUGGEST_TO_EDITOR: "phodit.editor.suggest.receive",
    GET_SUGGEST: "phodit.suggest.get",
    FULL_SCREEN: "phodit.fullscreen",
    UN_FULL_SCREEN: "phodit.unfullscreen",
    OPEN_GUIDE: "phodit.open.guide",
    SHOW_SLIDES: "phodit.show.echoesworks",
    SHOW_WORD: "phodit.show.word",
    SHOW_PDF: "phodit.show.pdf",
    GIT_STATUS: "phodit.git.status",
    OPEN_SYSTEM_PATH: "phodit.system.open.path",
  },
  CLIENT: {
    SAVE_FILE: "client.save.file",
    GET_SUGGEST: "phodit.editor.suggest.get",
    FULL_SCREEN: "phodit.editor.fullscreen",
    UN_FULL_SCREEN: "phodit.editor.unfullscreen",
    SHOW_WORD: "phodit.editor.show.word",
    SHOW_PDF: "phodit.editor.show.pdf",
    SHOW_TERMINAL: "phodit.editor.git.commit",
    HIDDEN_TERMINAL: "phodit.editor.hidden.terminal",
    OPEN_GUIDE: "phodit.editor.open.guide",
    TREE_OPEN: "tree.pub.open",
    FILE_MENU_CLICK: "tree.right.click",
    SHOW_SLIDES: "phodit.editor.show.slides",
    SEND_MARKDOWN: "phodit.editor.send.result",
    GET_RENDERER_MARKDOWN: "phodit.editor.get.result",
    SHOW_SIDE: "phodit.editor.showside",
    HIDDEN_SIDE: "phodit.editor.hiddenside",
    TOGGLE_THEME: "phodit.editor.theme.toggle",
  },
};
